AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.

Resources:
  redirect:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdaRedirect.handler
      Runtime: nodejs6.10
      Timeout: 3

  apigwRedirect:
    Type: AWS::Serverless::Function
    Properties:
      Handler: apigwRedirect.handler
      Runtime: nodejs6.10
      Timeout: 3
      Environment:
        Variables:
          PROTECTED_URL: https://08tquh0p3k.execute-api.us-west-2.amazonaws.com/test/api
          OPEN_URL: https://035rxrltw7.execute-api.us-east-2.amazonaws.com/test/api